# Generated by Django 2.2.4 on 2019-08-20 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190817_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 8, 20, 14, 6, 11, 460294, tzinfo=utc)),
        ),
    ]
